### ISSUE TITLE
Issue with DCW / New

### ISSUE THREAD

**Issue by Obsidiannite21** [Palleri/DCW#6]
Hello @Palleri, per our conversation in the other thread I rebuilt the container using the new image. Attached is what I see. Only 3 of the 42 active containers are listed. The "Updating" bar spins forever, even after I click check for updates. The only thing I changed in the compose file was the container. I thought it may be due to using the old data / config folder so I remove it and restarted the container. Unfortunately that didn't help. Attached is also the log.

![Screenshot 2023-07-13 at 3 46 56 PM](https://github.com/Palleri/DCW/assets/28603530/e1b859e6-6314-4237-9250-1b976e76546c)

      
Starting Dockcheck-web #
Checking for new updates #
This might take a while, it depends on how many containers are running #
Notify activated
WARNING: crond is already starting
DELETE 0
2023-07-13 15:45:16: (server.c.1568) server started (lighttpd/1.4.64)
2023-07-13 15:49:52: (server.c.2077) server stopped by UID = 0 PID = 0
Starting Dockcheck-web #
Checking for new updates #
This might take a while, it depends on how many containers are running #
Notify activated
rm: can't remove '/app/docker.tgz': No such file or directory
WARNING: crond is already starting

4
2023-07-13 15:50:12: (server.c.1568) server started (lighttpd/1.4.64)

**Comment by Palleri** [comment]
Hi @Obsidiannite21, 
That's odd. 
Do you have any other user setting up the container?
I see the UID and PID = 0

I will paste my configuration of my own setup.
Please paste your compose without sensitive information attached to it.

```yml
version: '3.2'
services:
  int-dockcheck-web:
    container_name: int-dockcheck-web
    hostname: HOST-DOCKER
    networks:
      int-prod:
        ipv4_address: 192.168.1.55
    image: 'palleri/dcw:latest'
    restart: always
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      TOKEN: xxxxxxxxx
      CRON_TIME: "16:00"
      NOTIFY: "true"
      NOTIFY_DEBUG: "false"
      NOTIFY_URLS: "xxxxxxxxxxxxxxxxxxxxxx"
      EXCLUDE: "xxxxxxx"
networks:
  int-prod:
    external: true
```

I am using macvlan so ignore the network settings.

`rm: can't remove '/app/docker.tgz': No such file or directory`
This line show if you restart the container. I always down my container to make sure everything is "removed and replaced" inside the container.

```
Notify activated
WARNING: crond is already starting
DELETE 0
```
These lines are expected, maybe not in the release but I've had some bughunting going on there. 
What browser are you using?
If not firefox, could you try to use that (it looks like there is a deeper problem with the container anyway, just trying to zero it down)

**Edit:** 
Right, I forgot. You are building it on your own right?
This is a multiplatform container and is build with some ARGs for ARM and such.
I use this command to build it

`docker buildx build --push --platform=linux/arm64/v8,linux/amd64 --tag palleri/dcw:latest . --no-cache`
Be aware of the `--push` it will send it to hub.docker.com

**Comment by Obsidiannite21** [comment]
Hello @Palleri 

Below is my docker compose config with * in place of sensitive information. To answer your questions:

I am not using any specific user settings, but please double check my compose to make sure. 

I am primarily using Safari, but I tried this on Chrome & Brave with the same results. 

I am not building it on my own. I only do that if I have to, and you were kind enough to post the container on Docker Hub.

Let me know if you need anything further.

version: '3.2'
services:
  dockcheck-web:
    container_name: dockcheck-web
    image: 'palleri/dcw:latest' # for new version when ready
    restart: unless-stopped
    ports:
      - '*:80'
    volumes:
      - /dockcheck/data:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      NOTIFY: "true"
      NOTIFY_URLS: "pover://*****
      EXCLUDE: "dendrite_postgres,nextcloud_mariadb,photoprism_mariadb,vikunja_mariadb,wordpress_mariadb,calcom_postgres,immich_proxy"

**Comment by Palleri** [comment]
@Obsidiannite21 
I am seeing that you are using the data folder to map the /var/www/html. 
Was that map empty before you started the new version? 
Or did you reuse that container to setup the new container over the old dockcheck-web? 
This could lead to a bunch of problems since I rebuild kind of the entire code of the container.
Recommendation is to not use the 
```
  volumes:
- /dockcheck/data:/var/www/html
```

I used your compose and it is working just fine.

**Comment by Obsidiannite21** [comment]
@Palleri As part of my troubleshooting I renamed that folder and restarted the new container when I first posted this issue. It created a new folder and the issue persisted. I’ve since re-named it back so  I’ll try again when I return home later tonight just to be certain but I don’t think that is the issue.

**Comment by Palleri** [comment]
@Obsidiannite21 
That folder mapping is not needed, so you can remove it. 
Regarding this I am concerned about the permissions when the folder is created. 
Because I think root is trying to create that folder for you and giving it ownership to "user 82". 
On top of that the html folder is not actually there. 
The root folder for the web is at /var/www 

Could you try to remove the image from the old dockcheck-web?
I have been struggling with one bug that is somehow connected to a layer on the old version of dockcheck-web.
I think I had to remove the image on the host and pull the new because of a layer conflict or something.
 
`# docker image ls` to list all the docker images.
`# docker image rm palleri/dockcheck-web:latest`
While you are at it, delete the DCW image aswell and let docker pull it again maybe.

What OS is DCW running on?

I am really thankful for your feedback and support regarding this troubleshooting. It helps me build a better version of DCW/dockcheck-web in the future.

**Comment by Obsidiannite21** [comment]
Absolutely, I’ll give all of that I try when I get home later tonight.

It is my pleasure, thank you for taking the time to create this project and share it with the rest of us.

**Comment by Obsidiannite21** [comment]
@Palleri Here is what I did:

I removed the container and both images. 
I commented out the config folder line in docker compose.
I re-created the container.

Unfortunately the issue persists. Attached is what I see now.

I'm running Ubuntu.

![Screenshot 2023-07-15 at 8 26 07 AM](https://github.com/Palleri/DCW/assets/28603530/4429d805-25aa-4f97-bdc6-a669a4423801)

**Comment by Palleri** [comment]
@Obsidiannite21
Hi, are you by any chance running with ipv6?  
 
Could you try to add 
`TOKEN: test123` or any string
Under your environment? 

Edit: 
Maybe stupid question, are you running 
`docker-compose down` after each attempt or are you running 
`docker-compose up -d` or `restart`?

**Comment by Obsidiannite21** [comment]
No, just ipv4.

I've added TOKEN: test123 to my compose file under environment. 

To Test a change like this I would do the following:

sudo docker stop dockcheck-web
sudo docker rm dockcheck-web
sudo docker-compose -f ~/docker-projects/ymls/docker-compose.dockcheck.yml up -d

Unfortunately the issue persists.

**Comment by Palleri** [comment]
All the containers are running with docker-compose and not docker run right? 
Do you see more containers if you press the dropdown at the left column right under "containers on latest version:"?

Could you try two different things, 
Remove the version at the top of the compose.
Remove the EXCLUDE part from the compose.

I cannot reproduce the issue you are having.
I dont know what your issue really is.
Is it that not every container shows up or is it that the web not function as it should?
On my setup I have more than 50 containers and it takes a while for the web to check for updates after pressing check for update.
It might take up to 1-7 minutes or more depending on the CPU and amount of containers.

After the container has started run this command to see if the database is populated with your containers.

`docker exec dockcheck-web psql -U postgres -d postgres "-AXtqc SELECT name FROM containers;"` 
where `dockcheck-web` `docker exec dockcheck-web ........` is the container name of yours.

You should see an output something like this;

nginx_web_1
rocketchat_mongo_1
joplin-app-1
dockcheck-web
flow-collector
joplin-db_jop-1
my-apache-app1
my-apache-app2
rocketchat_rocketchat_1
rocketchat_traefik_1

**Comment by Obsidiannite21** [comment]
I commented out the version & exclude line in the docker compose. Same result. Then I ran the exec command and it listed all of my containers. Then I re-read your message and noticed you mentioned a dropdown…. so I clicked it and all of my containers showed up. Wow, I’m so sorry I missed that. It was such a simple fix. That arrow wasn’t present in the previous version so I didn’t know it was there, or that I had to click it to list my containers. The only thing that is odd now is a container called d6697d716d32 in the latest version, update avilable, and containers with errors fields. I don’t have a container with that name so I’m not sure what it is.
![IMG_5432](https://github.com/Palleri/DCW/assets/28603530/33d50529-af61-4ce0-9655-0cef7da9c8b6)

**Comment by Palleri** [comment]
Hi, this is totally my fault haha. I didnt mention there was a dropdown in the first place.
The name (d6697d716d32) is the dockername that represent your host where containers are running from. 

Use `hostname: HOST-DOCKER` here to change this string.

```yml
......
dockcheck-web:
container_name: dockcheck-web
hostname: HOST-DOCKER              <-----------------##
image: 'palleri/dcw:latest' # for new version when ready
restart: unless-stopped
......
```

 I made the new DCW with the possibility to have [dcw-exporter ](https://github.com/Palleri/DCW-exporter). 
You can have multiple hosts and one web-gui to see all of your containers spreadout on multiple hosts.

Why I missed this myself is because the arrow is littlebit missplaced. I think its because you are using a different browser than me. The arrow should be placed next to the host name "d6697d716d32" in your case.

I have 50 containers spread out on multiple hosts, so the list became so long and people requested the ability to have a dropdown of some sort.

**Comment by Obsidiannite21** [comment]
Haha no worries. I’m glad we got it figured out! Thanks again for your help!

**Comment by Palleri** [comment]
You are welcome.
Thank you once again for using my project.
